### ISSUE TITLE
多次输入同一个问题，出现不同的答案

### ISSUE THREAD

**Issue by loopscn** [harusamei/zebura#21]
截图如第一个评论

**Comment by loopscn** [comment]
![ACD2BFA5-1D6B-4f22-9A91-2B4C66F5EABA](https://github.com/harusamei/zebura/assets/8383486/6946691d-52d0-4fdd-99ae-1f5d0bc15db2)

**Comment by harusamei** [comment]
比较可能的原因是LLM生成的回复不同， 走了不同的解析方法， 其中有一个方法有BUG，解析没成功；
