### ISSUE TITLE
像chatGPT那样的交互前端

### ISSUE THREAD

**Issue by harusamei** [harusamei/zebura#9]
https://github.com/Chainlit/chainlit
研究一下这个框架， 看是否能做为我们的系统前端
功能至少需要具备：
1.  区分登录用户
2. 记录每个用户的历史对话
3. 占击一个历史对话，可以继续对话
4. 输出类似CHATGPT那样的代码样式和表格样式
5.

**Comment by loopscn** [comment]
解决了一部分，你这个issue写得太范了。

**Comment by harusamei** [comment]
合并入 #27
